### ISSUE TITLE
problem with winding rules and boundery

### ISSUE THREAD

**Issue by udokrix** [visualdoj/fpc-libtess2#1]
Hallo visualdoj!

First let me thank you for porting libtess2 to fpc. While working with lazarus 1.8 under 32-bit openSuse I came across a problem, when
tessellating a polygon that I get when offsetting a square, which is orientated as CCR. It looks like this.

```
x --->--- x         x --->--- x
|         |         |         |
|         |         |         |
^   -1    v         ^    -1   v
|         |         |         |
|                             |
x ---<---------<---------<--- x

          |         |
          |    +1   |
          |         |

x --->--------->--------->--- x
|
|         |         |         |
^   -1    v         ^    -1   v
|         |         |         |
|         |         |         |
x ---<--- x         x ---<--- x
```

The x's are the vertices of the polygon, the numbers are the winding numbers as I understand them.    When tessellating it in the way you did it in the examples  with
        tessTesselate(tess, TESS_WINDING_POSITIVE, TESS_BOUNDARY_CONTOURS, 0, 2, nil)    
it should deliver the boundaris (4 vertices) of the inner square with winding number +1. Actually it delivers  the boundaries ( 16 vertices) of the four outer squares with winding number -1.      
       tessTesselate(tess, TESS_WINDING_NEGATIVE, TESS_BOUNDARY_CONTOURS, 0, 2, nil)
delivers the result I expected for the positive winding rule.

The values of the components of the vertices are integers. A strange thing is, that in others cases the correct results are deliverd, in other cases not as in the above example.

I the hope you can help me

yours Udo Krix

**Comment by visualdoj** [comment]
Hello!

I've reproduced the behaviour you described with both the port and the original libraries.

The last argument of the `tessTesselate` is `normal` which `libtess2` uses for projecting vertices onto internal `s,t`-plane. Winding rules are applied to the projected shapes, not the original ones, so `normal` implicitly affects actual meaning of CW and CCW, e.g. `normal=(0,0,+1)` and `normal=(0,0,-1)` are opposite cases. Moreover, if the `normal` argument is not provided, i.e. `nil` is passes like in the simple example and your code, `libtess2` tries to guess some "suitable" normal by computing signed area of the shape. It may reverse orientations of the contours after that process, see `CheckOrientation` function. If I understand correctly, that is the source of your problem.

To switch off that "auto orientation" mechanism you may pass your own `normal` explicitly. Suppose that we have "X right, Y down" coordinate system, then the normal is `(0, 0, -1)`:

```pascal
//
//                                             X
//    +------------------------------------------>
//    |
//    |     x --->--- x         x --->--- x
//    |     |         |         |         |
//    |     |         |         |         |
//    |     ^   -1    v         ^    -1   v
//    |     |         |         |         |
//    |     |                             |
//    |     x ---<---------<---------<--- x
//    |
//    |               |         |
//    |               |    +1   |
//    |               |         |
//    |
//    |     x --->--------->--------->--- x
//    |     |
//    |     |         |         |         |
//    |     ^   -1    v         ^    -1   v
//    |     |         |         |         |
//    |     |         |         |         |
//    |     x ---<--- x         x ---<--- x
//  Y |
//    v
//
const
CONTOUR_YDOWN_CCW: array[0 .. 12*2 - 1] of TESSreal = (
  1,  1,
  2,  1,
  2,  4,
  1,  4,
  1,  3,
  4,  3,
  4,  4,
  3,  4,
  3,  1,
  4,  1,
  4,  2,
  1,  2
);

NORMAL_DOWN: array[0 .. 2] of TESSreal = (0, 0, -1);

var
  tess: PTESStesselator;

  I, J, Count: LongInt;
  Indices: PTESSindex;
  Vertices: PTESSreal;

  NElems: LongInt;
  Elems: PTESSindex;
  Base: TESSindex;

  Normal: PTESSreal;

...


tessAddContour(tess, 2, @CONTOUR_YDOWN_CCW[0], 2 * SizeOf(TESSreal), Length(CONTOUR_YDOWN_CCW) div 2);
tessTesselate(tess, TESS_WINDING_POSITIVE, TESS_BOUNDARY_CONTOURS, 3, 2, @NORMAL_DOWN[0]);

NElems := tessGetElementCount(tess);
Elems := tessGetElements(tess);
Vertices := tessGetVertices(tess);
for i := 0 to NElems - 1 do begin
  Base := elems[i * 2];
  Count := elems[i * 2 + 1];
  for J := 0 to Count - 1 do begin
    Writeln(Vertices[2 * (Base + J)]:0:2, ' ', Vertices[2 * (Base + J) + 1]:0:2);
  end;
  Writeln;
end;
```

It prints the central square you expect.

Let me know if it solves your problem.

**Comment by udokrix** [comment]
issue #1 solved
I misunderstood the comment "of null the normal is calculated automatically"  to the last parameter "normal" of the function "tessTesselate(... normal)" when passing "nil". With my own normal vector (0,0,1) it worked as it should. Thanks to "visuldoj" for the decisive hint.

Udo Krix.
